name: SDM Record Deployment workflow

on:
  workflow_run:
    workflows: [Sample customer workflow]
    types:
      - completed

jobs:
  sdm-record-deployment-job:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
