name: SDM Record Deployment

on:
  workflow_run:
    workflows: [Sample customer workflow]
    types:
      - completed

jobs:
  sdm-record-deployment:
    runs-on: ubuntu-latest
    steps:
          - run: echo '$github.event.workflow_run'
